### ISSUE TITLE
C-y yank not doing anything

### ISSUE THREAD

**Issue by fommil** [stsquad/emacs_chrome#112]
If I `M-w` some text and then `C-y`, nothing is yanked.

Also, if I have something in my clipboard, e.g. from an external application such as emacs, the `C-y` isn't working either.

Is this supposed to work?

**Comment by fommil** [comment]
sorry, wrong project.

**Comment by stsquad** [comment]
Now I'm curious to what project you thought it was ;-)

**Comment by fommil** [comment]
ChromEmacs... Emacs bindings.
