### ISSUE TITLE
Changes in Emacs aren't reflected in the textbox

### ISSUE THREAD

**Issue by zachlatta** [stsquad/emacs_chrome#115]
I've having a bit of trouble getting textboxes on the webpage to reflect my changes in Emacs.

Any thoughts on where to start debugging this? No errors in the JavaScript and the only output from the plugin with debugging on is `findTextAreas: running over 1` from `textareas.js`.

![recorded](https://cloud.githubusercontent.com/assets/992248/9067248/27017906-3a91-11e5-8aea-86afbf071848.gif)

**Comment by zachlatta** [comment]
Nevermind... I wasn't hitting `C-c C-c` when done.

**Comment by stsquad** [comment]
I wonder if there is clearer feedback the Chrome frame could give when the user cancels and edit?
