### ISSUE TITLE
Hooking to edit-server-mode-hook caused error "Lisp nesting exceeds 'maxlisp-eval-depth'"

### ISSUE THREAD

**Issue by ReneFroger** [stsquad/emacs_chrome#116]
Thanks for sharing this awesome package. It's really appreciated. However, I ran into problems which I couldn't figure it out.

# Bug report

## Setup:
GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)
of 2015-07-25 on KAEL
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
edit-server, using the latest version of edit-server from MELPA
Windows 7 x64 bit.

## Situation:

In my `init.el`, I have the following setup:

    (setq edit-server-new-frame nil)
    (edit-server-start)

Everything works fine. Emacs and Chrome are working fine togheter.

When I add the following:

    (add-hook 'edit-server-edit-mode-hook 'markdown-mode)

And when I want to edit a textfield from Chrome in Emacs, I get the following error:  

    Error in post-command-hook (global-edit-server-edit-mode-check-buffers): (error "Lisp nesting exceeds `maxlisp-eval-depth'"). 

After googling around, someone said this might help: 

    (setq max-specpdl-size 50)

But it didn't help. When I get that error message, I also noticed that my keybindings are behaving weird.

So I'm puzzled what caused this error, when I hook the `markdown-mode` to the `edit-server-edit-mode-hook`. Any reason why I get the error message?

**Comment by stsquad** [comment]
Generally that error message indicates you've gone into a infinite recursive loop and eventually you run out of stack. Setting `debug-on-exit` or `debug-on-quit` would allow you to get a better backtrace. For some reason the docstring seems to be bust but:

    "Hook run when we enter edit-server-edit-mode.  This is the final step of
    an edit session and is called when all frames and displays have been
    set-up.  You should not set any additional major modes here though as they
    may conflict with the edit-server-edit-mode, use the
    edit-server-start-hook instead."

The correct way of setting the major mode is either use `edit-server-start-hook` or the even more handy `edit-server-url-major-mode-alist` which is useful for selecting a mode based on the URL you are editing, eg:

    (add-to-list 'edit-server-url-major-mode-alist
                     '("github.com" . markdown-mode))

I'll have a look into why the docstring isn't showing up properly as it adds to the confusion.

**Comment by ReneFroger** [comment]
@stsquad thanks for your helpful answer. Note that I use `eldoc-mode`. It enables you to see documentation of any variable/function directly in your minibuffer. 

You can enable it with 

    (add-hook 'emacs-lisp-mode-hook 'eldoc-mode)

So when your cursor/pointer is on a function, you see the string documentation inside your minibuffer. I notice there is stringdocumentation about `edit-server-edit-mode-hook`:

    Hook run Hook run after entering or leaving ‘edit-server-edit-mode’.

Maybe it would be a idea to expand the string documentation with `Don't use this hook, use edit-server-start-hook instead.`? Your answer helped me a lot, I really appreciate it.

**Comment by stsquad** [comment]
@ReneFroger that's the thing the docstring does say that, but it's wrapped in a defcustom so I wonder if that's what is confusing things?
