### ISSUE TITLE
Suddenly stopped with working on Ubuntu, runs fine with same conrfig on Windows

### ISSUE THREAD

**Issue by ReneFroger** [stsquad/emacs_chrome#118]
Hi there! Thanks for creating this awesome package.

I use Emacs 25.0.50, with Ubuntu 15.10 and Windows 7

But for unclear reasons, edit-server don't work anymore on Ubuntu with Chrome. Earlier it was running fine. The weird thing, is that the same configuration on Windows 7 (same Emacs version), it stil works fine with Chrome.

When I click on "test" in the Emacs edit-server extension on chrome, with "Enable debug (logs to the console)" toggled, I see nothing in the console. Emacs is running in thte background. In the Emacs instance, I call <kbd>M-x</kbd> `edit-server-start`, then I get the message `An edit-server process is already running`. 

But nothing happens when I call for edit server in a text area, via context-menu or via edit button next to textarea or via Alt-Enter, while all three are enabled in the configuration. The edit server host (127.0.0.1) and edit server port (9292) are still the same.

How could I find the culprit that halted my edit server?

**Comment by stsquad** [comment]
Well lets start with:
    netstat -ltpn

And see if emacs has a socket open listening for edit-server requests.

**Comment by ReneFroger** [comment]
Yes, one of the results listed, after entering `netstat -ltpn`

> tcp        0      0 127.0.0.1:9292          0.0.0.0:*               LISTEN      2085/emacs      

So there seems a socket to be open, listening for edit-server requests.

**Comment by ReneFroger** [comment]
Yes, one of the results listed, after entering `netstat -ltpn`

> tcp        0      0 127.0.0.1:9292          0.0.0.0:*               LISTEN      2085/emacs      

So there seems a socket to be open, listening for any edit-server requests. So there must be something went wrong in the connection between the socket and the browser. How could I check that?

**Comment by stsquad** [comment]
OK the next thing to try is running the edit-server with logging enabled:

    M-x edit-server-stop
    C-u M-x edit-server-start
    
And see if the edit server got any message from the extension but just got confused.

**Comment by ReneFroger** [comment]
It suddenly worked now! And I haven't really an idea what caused this. It didn't worked earlier after restarting Emacs and OS several times. 

Thanks for your help, the issue seems to be solved on itself. But thanks anyway!
