### ISSUE TITLE
Make the inserted <img> button more customizable

### ISSUE THREAD

**Issue by angrybacon** [stsquad/emacs_chrome#120]
By making it a `<div>` with `background-image` instead for example.

As of now and in all browsers, replaced content (such as for `<img>`) have no `:before` nor `:after`. This makes it impossible to customize the button appearance with a custom stylesheet.

**Comment by stsquad** [comment]
I've had a brief look but it looks like defining the extensions CSS background-image property in textarea.css would involve hardcoding the image url with the extension ID. I suspect the work around is to inject the CSS directly into the page.

**Comment by stsquad** [comment]
Does https://github.com/stsquad/emacs_chrome/tree/div-background-image-exp meet your needs? I think it's ready to be merged now.

**Comment by angrybacon** [comment]
I'll have to check this out when I get the time. Thanks, will give feedback as soon as possible!

**Comment by angrybacon** [comment]
That works :-)

With more time I might just contribute a field where users can add their own style so they don't have to rely on yet another extension.

Thanks a lot.
