### ISSUE TITLE
If not exist one emacs frame exist, click icon in toolbar could not create new frame.

### ISSUE THREAD

**Issue by zw963** [stsquad/emacs_chrome#132]
if no emacs frame keep opened, when I click emacs icon in toolbar,
i will see that icon change it color to `green`, when cursor on, i can see
`Edit request sent for ....`,  But not any new frame is created.

if i keep one frame is opened, and press emacs icon again, it worked as expect.

**Comment by stsquad** [comment]
This works for me. Is edit-server-new-frame set for you?

**Comment by zw963** [comment]
@stsquad , it default is true, i am not change it.

**Comment by zw963** [comment]
I am weird if some following issue cause is. (I guess, because it happen to me before)

1. emacsclient, without `-c` arg, only with -c will create new frame.
2. I export some environment variable, which affect this.

**Comment by zw963** [comment]
I think, this issue is reuse a exists frame, not create a new frame.

**Comment by stsquad** [comment]
I wonder if that was broken by:
  https://github.com/stsquad/emacs_chrome/commit/0a50fbb524fe256560f481701c000309c627b9ca

**Comment by zw963** [comment]
@stsquad ,  Yes, after I revert that commit, it worked now.

**Comment by stsquad** [comment]
So I think what is happening is the emacs --daemon is being started without DISPLAY set, hence breaking the new frame. I don't see it as I start my GUI daemon's with DISPLAY set.

**Comment by zw963** [comment]
> So I think what is happening is the emacs --daemon is being started without DISPLAY set, hence breaking the new frame. I don't see it as I start my GUI daemon's with DISPLAY set.

Not understood completely about what you said, so, what the solution?

my emacs start process like following

```sh
zw963     4054  2.6  0.4 482984 159304 ?       Ssl  16:02  12:10 /usr/local/bin/emacs -l ~/Dropbox/common/.emacs.d/set_load_path.el --daemon=zw963
```

**Comment by stsquad** [comment]
If you run:
    emacsclient -e '(getenv "DISPLAY")'

What do you get?

**Comment by zw963** [comment]
> If you run:
> 
> emacsclient -e '(getenv "DISPLAY")'
> 
> What do you get?

```sh
 $ emacsclient -e  '(getenv "DISPLAY")'
":0"
```
