### ISSUE TITLE
Nothing happens if only emacs --daemon is running

### ISSUE THREAD

**Issue by DirkSchmitt** [stsquad/emacs_chrome#133]
Description
---------- 
My personal setup is *emacs* running in daemon mode.
If all „frames“ are closed, but the daemon still running I can't open a new frame with Edit with Emacs.

The problem is mitigated if at least 1 frame is opened again

Environment
-----------
- emacs25
- firefox 57.0.4
- edit with emasc 1.14

Startup code:

```
(require 'edit-server)
(when (daemonp)
  ; customise to have full menu
  (setq  edit-server-new-frame-alist
         '((name . "Edit with Emacs FRAME")
           (width . 80)
           (height . 25)))
  ; preset some per domain mode settings
  (setq edit-server-url-major-mode-alist
        '(("github\\.com" . markdown-mode)))
  (edit-server-start))
```

**Comment by stsquad** [comment]
Is this the same symptoms as #132? I'd like to see what (edit-server-start 4) leaves in the logs.

**Comment by stsquad** [comment]
Ahh I think this is the regression from:

    (if (memq window-system '(ns mac nil))
        ;; Aquamacs, Emacs NS, Emacs (experimental) Mac port, termcap.
        ;; matching (nil) avoids use of DISPLAY from TTY environments.
        (make-frame edit-server-new-frame-alist)
      (make-frame-on-display (getenv "DISPLAY")
                                       edit-server-new-frame-alist)))

**Comment by stsquad** [comment]
Can everyone test the latest master?

**Comment by DirkSchmitt** [comment]
1st Test is successfull :-)

I killed `emacs --daemon` and replaced `edit-server.el`with the current version from github.
After that run `emacs --daemon` again and start editing this comment with *Edit with Emacs*.

**Comment by stsquad** [comment]
OK closing as fixed. Thanks for your test.

**Comment by zw963** [comment]
This worked for me too after update new `edit-server.el`.
Even, i restart my emacs daemon, and never open any frame, 
i still could invoke emacs frame now.

Thanks very much for this.

Emacs version: 26.1, Arch linux
