### ISSUE TITLE
firefox?

### ISSUE THREAD

**Issue by titaniumbones** [stsquad/emacs_chrome#137]
any instructions for how we ought to try to install on firefox? Thanks!

**Comment by stsquad** [comment]
one for @dakra to answer I think.

**Comment by dakra** [comment]
I see there is no link to AMO in the readme.

@titaniumbones  You can install the extension simply from
https://addons.mozilla.org/en-US/firefox/addon/edit-with-emacs1/

And then it's best to install `edit-server` from melpa and configure
like described in the readme.

If you use `use-package` something like this should do:
```emacs-lisp
(use-package edit-server
  :config
  (setq edit-server-url-major-mode-alist
        '(("reddit\\.com" . markdown-mode)
          ("github\\.com" . gfm-mode)
          ("gitlab\\.com" . gfm-mode)))
  (edit-server-start))
```
