### ISSUE TITLE
Bad use of `edit-server-frame`

### ISSUE THREAD

**Issue by elibarzilay** [stsquad/emacs_chrome#138]
I just update `edit-server.el`, and now I'm getting a warning on every edit:

    delete-window: Attempt to delete minibuffer or sole ordinary window

I'm guessing that this comes from the `(unless edit-server-frame ...)`
which is done after the frame is deleted and the buffer is killed and
therefore it is now testing the default value of the variable instead of
the actual value.

I worked around this by adding a `(frame edit-server-frame)` to the top
`let`, and that seems to work.  I can make a pull request if this is the
right fix.  (I'm not sure about it, for some reason I see that this
function is called twice, with the dead frame object on the second
call.)

**Comment by dakra** [comment]
Ups, that's a bug I introduced and it should only delete the window
when `edit-server-new-frame` is set to `nil`.

But looks like I mixed up the variable name, can you change
`edit-server-frame` to `edit-server-new-frame` here
https://github.com/stsquad/emacs_chrome/blob/672d0f421006f77444b00c4c4ca6de01b9c2ae48/servers/edit-server.el#L647
and tell me if that works then?

Thanks.

**Comment by elibarzilay** [comment]
Yeah, that makes more sense, and so far it looks like it's working fine.
