### ISSUE TITLE
Edit in Firefox via context menu doesn't work

### ISSUE THREAD

**Issue by lujun9972** [stsquad/emacs_chrome#142]
I right click the text box and select the "Edit with Emacs", a new frame appears.
Then I input the content and press "C-x #" (and "C-c C-c" either),the frame disappears with nothing filled into the text box

**Comment by dakra** [comment]
Are you using chrome or Firefox? And does it happen on all websites or just some? If so, is it public?

**Comment by lujun9972** [comment]
I am using firefox, and I tried on the github

**Comment by dakra** [comment]
How did you invoke 'Edit with Emacs'?
In Firefox on some sites the context menu way is broken
and it behaves the way you described.

It's probably an easy fix but I didn't have time yet
and it doesn't bother me as I always use 'M-RET' in
a selected textfield or use the toolbar button.

**Comment by lujun9972** [comment]
I'm using archlinux and the firefox version is 58.0.2 (64-bit)

**Comment by lujun9972** [comment]
I press the 'M-RET' but nothing happened.

**Comment by lujun9972** [comment]
But the toolbar button works fine,thanks

**Comment by lujun9972** [comment]
Should I keep this issue open or close it?

**Comment by dakra** [comment]
You have to activate 'ALT Enter' in the options first.

I guess you can keep it open as a reminder.
Maybe change the title to `Edit in Firefox via context menu doesn't work`
or something along those lines.

Thanks.

**Comment by stsquad** [comment]
Closing old bugs
