### ISSUE TITLE
Firefox extension interface config invalid.

### ISSUE THREAD

**Issue by zw963** [stsquad/emacs_chrome#153]
following config not working

![DeepinScreenshot_select-area_20181013011712.png](http://zw963.github.io/images/166062770231292.png)

1. when checked, edit button is not shown in current github textarea.
2. when not checked, i still could see context menu when click mouse right button.
~~3. when checked, double click not work~~
~~4. when checked, `Alt + Enter` not work~~

Current i use two way to open emacs frame.

1. mouse right button to open
2. click emacs extension icon to open

Those work well for me.

Firefox version: 63.0b12 (64-bit) Developer version, Arch Linux 64bit

**Comment by zw963** [comment]
After reload website, `Alt+Enter` and `double click` worked now.
Thanks

**Comment by stsquad** [comment]
Seems user has fixed issue, closing

**Comment by zw963** [comment]
Show edit button is worked now?

**Comment by stsquad** [comment]
@zw963 sorry didn't realise you still had an issue. It's confusing having so many different issues in one bug.

**Comment by zw963** [comment]
It working for current verison firefox. 73.0.2 (64-bit), nightly, thank you.
