### ISSUE TITLE
get "-error Authentication&_failed" error when use emacs_chrome in another linux

### ISSUE THREAD

**Issue by zw963** [stsquad/emacs_chrome#156]
i current use another laptop, `Deepin GNU/Linux 15.7`, Firefox: 64.0beta2 developer version
with builtin emacs verison 25.2.2

And, i config this plugin use correct port to emacs daemon. when try to start emacs frame in 
firefix, got: `-error Authentication&_failed` message.

But, same Firefox version +  Arch Linux with builtin emacs 26.1 worked in another laptop.

Thanks.

**Comment by dakra** [comment]
Where do you get this error? And exactly only this or is there more context? I haven't seen this before and this error message is not very google friendly.

**Comment by zw963** [comment]
![DeepinScreenshot_select-area_20181025185331.png](http://zw963.github.io/images/177761900619925.png)

if click plugin emacs icon, this error message is fill in current textarea.

**Comment by zw963** [comment]
Not use that OS anymore, closed.
