### ISSUE TITLE
Configurable shortcut

### ISSUE THREAD

**Issue by skybert** [stsquad/emacs_chrome#165]
Hitting `Alt` + `Enter` doesn't work on my system (don't know if it's `i3`, the website or Firefox which grabs it) and I would therefore like to specify another shortcut that I'm sure on my desktop.

**Comment by arialdomartini** [comment]
I confirm the same with i3, Firefox, on Linux.

**Comment by skybert** [comment]
Something has changed, don't know what. This works for me now using i3, Firefox on Linux:
- github issue comment :+1: 
- Bitbucket PR comment :+1: 

However, one of the apps I can't live without, doesn't:
- Jira comment :-1: 
- Jira issue description: :-1: 

I assume it's Jira that grabs it, so I need a way to configure the shortcut :thinking:

**Comment by HarrisonMc555** [comment]
I haven't been able to find out where to customize the keyboard shortcut. I also haven't been able to get "Option+Enter" (I'm on macOS) to work anywhere yet. Double click and clicking the "edit" button work though!

**Comment by stsquad** [comment]
So with the branch: https://github.com/stsquad/emacs_chrome/tree/ui/use-chrome-shortcuts you should find Keyboard shortcuts on the chrome://extensions/ page under the burger toolbar in the top left corner.

**Comment by HarrisonMc555** [comment]
Oh, so do I need to check out that branch, build the extension, and install it from my local copy then?

**Comment by stsquad** [comment]
Check out the branch and then just select "Load Unpacked" extension and point it at the directory. No building should be required.

**Comment by HarrisonMc555** [comment]
Ok that did it! Thanks so much for your help.

**Comment by stsquad** [comment]
If it's working well for you let me know and we can merge the branch for the next release.

**Comment by HarrisonMc555** [comment]
It is working! The only "gotcha" I faced was that I needed to refresh pre-existing tabs before I could use the keyboard shortcut. Once I did that, everything worked fine.

**Comment by stsquad** [comment]
OK I've merged that branch to master so it will be in the next release.
