### ISSUE TITLE
Do not suggest adding ~/.emacs.d to load-path

### ISSUE THREAD

**Issue by phil-s** [stsquad/emacs_chrome#166]
`emacs_chrome/fancy-settings/source/i18n.js` says:

> Save the file to somewhere visible to your your Emacs <code>load-path</code> (<code>~/.emacs.d</code> is popular) and add the following to your <code>.emacs</code>:
>
>          (add-to-list 'load-path "~/.emacs.d")

No one should have `~/.emacs.d` in their `load-path`.  Sub-directories are fine, but it's unsafe to use that directory itself.  For quite some time Emacs has even issued a [warning](https://emacs.stackexchange.com/q/9877) if you do this, so at minimum your suggestion can cause *that* to happen, which is also an undesirable result.

I suggest you change the text to say "(`~/.emacs.d/lisp` is popular)" instead.

**Comment by stsquad** [comment]
Thanks. Fixed.
