### ISSUE TITLE
Can't use edit-server when using command+tab

### ISSUE THREAD

**Issue by parhamdoustdar** [stsquad/emacs_chrome#168]
Hi,

I'm using the latest MacOS and Emacs 29.0.50. Here is how I try to use edit-server:

1. I have `edit-server-new-frame` set to `nil`. I use Emacspeak, so a buffer would be a lot easier for me to use than a new frame.
2. I do C-u -x edit-server-start.
3. Then, I go to a text box, and I press Command+e. I'm blind, so I don't see what happens on the screen, but when I use COmmand+tab to go to the Emacs window and edit the buffer, this is what the `*Messages*` buffer says:

```
accept from 127.0.0.1

Got HTTP ‘POST’ request of url ‘/foreground’, processing in buffer ‘ *edit-server*-948322’...
Processed headers, length: 11, url: nil, file: nil
sending edit-server response
Editing done, sent HTTP OK response.
```

It seems like when I press Command+tab, since I leave the text box, edit-server sends the response. So, I feel like I'm supposed to use this package in a form I don't quite understand.

Could you give me any pointers?

Thanks!

**Comment by stsquad** [comment]
Ahh I think we have a documentation or UI errror. That is because Command+e issues a foreground command which was added to bring Emacs to the foreground with the contents of the clipboard. The command that activates the editing is Alt+e by default.

**Comment by stsquad** [comment]
I've just realised the keyboard shortcut isn't enabled by default - it in the extension configuration tab under settings/configuration/interface and the check boxes for the enabling the various methods to invoke the editor. The default method is to click the edit button that floats near each text box which I'm guessing isn't super accessible for visually impaired users.

If you have any suggestions for how to improve accessibility please let me know and I'll do my best to improve it.

**Comment by parhamdoustdar** [comment]
q

**Comment by parhamdoustdar** [comment]
Ah, I think I was not using Chrome's interface for setting the keystroke to activate the extension correctly. Now that I tried again, pressing the key that I assigned to "Activate extension" makes it all work.

Awesome! This extension is going to help me a lot with VoiceOver's shortcomings in Chrome! You made me life so much easier 😍
