### ISSUE TITLE
edit-server is not in elpa, update README?

### ISSUE THREAD

**Issue by colourful-land** [stsquad/emacs_chrome#169]
Using emacs 26 from Ubuntu 20.04.

First,  go to website https://elpa.gnu.org/ and clikc "Browse Packages", edit-server is not in the list

Try again in emacs. Do `m-x list-packages` shows this list that doesn't have edit-server either.

````
      Package            Version       Status [v] Description                   
 55   disk-usage         1.3.3         available  Sort and browse disk usage li$
 56   dismal             1.5           available  Dis Mode Ain't Lotus: Spreads$
 57   djvu               1.1           available  Edit and view Djvu files via $
 58   docbook            0.1           available  Info-like viewer for DocBook
 59   dts-mode           0.1.0         available  Major mode for Device Tree so$
 60   easy-kill          0.9.3         available  kill & mark things easily
 61   ebdb               0.6.18        available  Contact management package
 62   ebdb-gnorb         1.0.2         available  Utilities for connecting EBDB$
 63   ediprolog          1.2           available  Emacs Does Interactive Prolog
 64   eev                20200224      available  Support for e-scripts (eepitc$
 65   eglot              1.6           available  Client for Language Server Pr$
 66   el-search          1.12.6.1      available  Expression based interactive $
 67   eldoc              1.0.0         available  Show function arglist or vari$
 68   eldoc-eval         0.1           available  Enable eldoc support when min$
 69   electric-spacing   5.0           available  Insert operators with surroun$
 70   elisp-benchmarks   1.5           available  elisp benchmarks collection
 71   enwc               2.0           available  The Emacs Network Client
 72   epoch-view         0.0.1         available  Minor mode to visualize epoch$
 73   ergoemacs-mode     5.16.10.12    available  Emacs mode based on common mo$
 74   excorporate        0.8.3         available  Exchange Web Services (EWS) i$
````

So how did everyone else get their `edit-server`? Thanks.

**Comment by dakra** [comment]
In GNU Elpa are official GNU Emacs packages only
and all contributors to those have to have the Copyright assignments
signed etc.

Most packages are hostet on [melpa](https://melpa.org/#/).
You should definitely add this package repo to your Emacs config,
a lot of great and very popular packages (like magit) are there.

**Comment by stsquad** [comment]
As it happens I have signed the GNU copyright assignment license which I needed for my contributions to ivy/counsel. However the edit-server has had a lot of people work on it over the years so we would need to track them all down and verify their assignment status. If someone is willing to do the work tracking everyone who has worked on edit-server.el down then I'll happily support hosting the edit-server.el on elpa.

**Comment by colourful-land** [comment]
Let's not turn a task into a project - I reworded the issue to just ask for the documents to be updated so that the user will go to melpa instead of wasting time and search into github issues to find a solution, and let the project (copyright assignment) go on at its own pace.

**Comment by stsquad** [comment]
Having just double checked the readme already says:

    You can also install edit-server.el via MELPA:

So I guess we need this to be more prominent elsewhere?

**Comment by colourful-land** [comment]
Thanks.
