### ISSUE TITLE
Firefox v1.16 release needs to be made

### ISSUE THREAD

**Issue by stsquad** [stsquad/emacs_chrome#174]
Hi @dakra just a place holder to let you know I've tagged v1.16 and pushed to the chrome webstore. Could you do the same for the Firefox side when you get a chance?

**Comment by dakra** [comment]
Thanks.

Personally I switched to atomic-chrome/GhostText.

But I'll see that I can make a release in the coming week.

**Comment by dakra** [comment]
Finally got around to publish the release.

This message is written with emacs_chrome but someone else should please also test.

https://addons.mozilla.org/en-US/firefox/addon/edit-with-emacs1/

**Comment by stsquad** [comment]
Tested and it works, thanks @dakra.
