### ISSUE TITLE
Doesn't work on Brave: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by aspiers** [stsquad/emacs_chrome#179]
This extension has inexplicably stopped working on Brave (or maybe never worked).  My server is very definitely running on port 9292 (I can even `telnet localhost 9292` with no problems) but the browser refuses to connect to it.

If I open the Test page (`fancy-settings/source/index.html`) and the background page (`html/background.html`), and click the Test button, I see a `GET http://127.0.0.1:9292/status net::ERR_BLOCKED_BY_CLIENT` error on the background page's console:

![image](https://user-images.githubusercontent.com/100738/113507095-66cba600-9540-11eb-86ca-1010d5d30cf5.png)

from this source:

![image](https://user-images.githubusercontent.com/100738/113507142-9ed2e900-9540-11eb-8878-45c20806bc74.png)

**Comment by aspiers** [comment]
This was on Brave version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit).  I have also just tested on Google Chrome version 89.0.4389.72 (Official Build) (64-bit) and it works perfectly.  The same goes for Atomic Chrome which also uses websockets on `localhost`.  So this appears to be an issue with Brave :-(

**Comment by stsquad** [comment]
We currently don't use websockets - just a plain HTTP over TCP connection. Either way it seems the problem is with Brave and not Edit with Emacs.

**Comment by aspiers** [comment]
Thanks for the clarification.

**Comment by LucaColombi** [comment]
same net::ERR_BLOCKED_BY_CLIENT accessing a resource from localhost

**Comment by Pritam055** [comment]
just worked for me when i disabled the adblock in brave.. try it!

**Comment by ScottJWalter** [comment]
If you turn off Brave's security features ("shields down"), it works just fine.  And the constant reference to different "localhost" configuration settings that don't exist doesn't help matters.
