### ISSUE TITLE
"Edit with Emacs" is slowing down Firefox

### ISSUE THREAD

**Issue by wentasah** [stsquad/emacs_chrome#183]
I'm getting the `"Edit with Emacs" is slowing down Firefox` message on a page with a big table (see below). On that site, Firefox UI is really unresponsive for a few seconds. Is there a way how to debug the problem?

I know very little about javascript, but my guess is that the [for loop in `findTextAreas`](https://github.com/stsquad/emacs_chrome/blob/1632acab5624637031326bd902e2ad7ccb6b4c90/javascript/textareas.js#L336) executes for too long. If this is the case, would it be possible to split the loop to smaller pieces or execute is somehow in background, so that it doesn't block the UI?

![edit-with-emacs-brute](https://user-images.githubusercontent.com/140542/154666505-1a45afb5-fd0d-4a2b-af23-c8ee2821dbcb.png)

**Comment by stsquad** [comment]
Yeah I suspect this is a very heavy page to be doing a dumb iteration over all the elements. I suspect jQuery could come up with a better subset of elements to check through rather than testing their type in findTextAreas.

**Comment by stsquad** [comment]
Could you try the current state of master and see if things have improved.

**Comment by wentasah** [comment]
Yes, it has improved a lot. When I load the mentioned page, I don't notice any UI blocking. Thanks!

**Comment by stsquad** [comment]
OK thanks for testing - this will roll into the next release.

**Comment by stsquad** [comment]
No immediate plan. I need to clean up the multi-browser handling (polyfill) and then figure out the publishing via my user account as I think @dakra has moved on from doing that side of things. Using the signed extension is not overly hard (although I had to jump through hoops on my Flatpak version of Firefox).

**Comment by dakra** [comment]
Right, I use a different package now. I'm happy to transfer the project to your account so users don't have to install a different extension and you keep the 5 star reviews ;)
Publishing was simple with `web-ext`. I can also do it one more time for you if you want.
But long-term, probably better if everything is in your hands.

**Comment by stsquad** [comment]
> Right, I use a different package now. I'm happy to transfer the project to your account so users don't have to install a different extension and you keep the 5 star reviews ;) Publishing was simple with `web-ext`. I can also do it one more time for you if you want. But long-term, probably better if everything is in your hands.

Ahh if you can transfer it to my Firefox id that would be great (it's also stsquad).

**Comment by dakra** [comment]
It needs an email. I tried your linaro address that you use for commits but it doesn't find you.

**Comment by stsquad** [comment]
> It needs an email. I tried your linaro address that you use for commits but it doesn't find you.

Try alex@bennee.com

**Comment by dakra** [comment]
:+1: done
