### ISSUE TITLE
keyboard shortcut needs to be configurable and have a better default

### ISSUE THREAD

**Issue by aspiers** [stsquad/emacs_chrome#21]
Alt-E is a standard Chrome keyboard shortcut for opening one of the two main Chrome menus (the other is opened with Alt-F).  So I'm not sure how Alt-E in this extension could ever invoke the editor.  So the default shortcut should be better, but more importantly it should be configurable by the user.  Thanks!

**Comment by spiderbit** [comment]
OK 
1. the function would be "editTextArea"
2. you can't directly call functions from another extension

So you would need to add a messagehandler I guess:
https://developer.chrome.com/extensions/messaging#external

Would that make sense and would that at least partially fix this bug? Or go beyond that?

Should not be that hard to do, would that go into upstream?

**Comment by stsquad** [comment]
As long as it doesn't regress the current default behaviour I'll merge things to make it more configurable.

**Comment by spiderbit** [comment]
I give it maybe a try then at some point :D need to use your addon first... just installed it today... I might have already a bug, I think it does not load the input-method... but I should open a new bug for that...

I just have a few other things I want to address before that goes up my list :D

**Comment by stsquad** [comment]
I think all the keyboard triggers are now the domain of the browser itself. I've tested this on both Chrome and Firefox.
