### ISSUE TITLE
Edit Server Error's "I'll take you to the options page..."

### ISSUE THREAD

**Issue by lalopmak** [stsquad/emacs_chrome#88]
In normal usage, I've found the forced "I'll take you to the options page when you close this" feature of the "Unable to contact an edit server" error popup to be very annoying.  Two main reasons:
1. Normally, this is due to the edit server being inactive for some reason, an external problem that requires restarting it rather than a detour to the settings.
2. In case it really doesn't work for some reason, a new error popup is created every time you try.  Closing them leads to opening the options page an untold number of times.

The only time it might really be useful is during initial configuration, ultimately a minority of a user's lifetime.

An ideal fix might just be an optional link to that options page.  Merely disabling it, providing an option to disable it, or preventing multiple popups would be wonderful, however.

Thank you!

**Comment by stsquad** [comment]
@lalopmak if you still care can you test master and let me know if I can close this issue?
